# For more information visit: https://docs.helix.ml/helix/private-deployment/environment-variables/
envVariables:
  LOG_LEVEL: debug
  APP_URL: http://localhost:8080
  # Database
  POSTGRES_HOST: my-helix-controlplane-postgresql
  POSTGRES_USER: helix
  POSTGRES_PASSWORD: oh-hallo-insecure-password
  POSTGRES_DATABASE: helix
  # Runners
  RUNNER_TOKEN: oh-hallo-insecure-token
  # LLM providers
  INFERENCE_PROVIDER: "togetherai" # Valid values: togetherai, openai, helix
  FINETUNING_PROVIDER: "togetherai" # It's likely you want to use the same provider for both
  OPENAI_API_KEY: ""
  TOGETHER_API_KEY: "a69051a4636bf946a6418bbf288452e4df57b2e3e153806e4680e702e6556da0"
  # Keycloak location
  KEYCLOAK_URL: http://keycloak:80/auth
  # How Keycloak redirects the users on login, should be user facing
  KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
  KEYCLOAK_USER: "admin"
  KEYCLOAK_PASSWORD: "oh-hallo-insecure-password"
  # Dashboard
  ADMIN_USER_IDS: "all"
  # Evals 
  EVAL_USER_ID: ""